version: '3'

services:

  frontend:
    container_name: optima-gui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/gui'
      - '/gui/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
