version: '3.7'

services:
  web:
    build: .
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000

    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    env_file:
      - .env
    expose:
      - 5432
  redis:
    image: redis:latest
    expose:
      - 6379
    volumes:
      - redis-data:/data
volumes:
  database-data:
  redis-data:

networks:
  default:
    external:
      name: inetwork
